server:
  port: 8090
spring:
  druid:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: zhihu
    password: zhihu
    maxActive: 30 #最小连接数
    minIdle: 5 #最大连接数
    maxWait: 10000 #获取连接的的最大等待时间
    timeBetweenEvictionRunsMillis: 6000 #空闲连接检查时间间隔
    minEvictableIdleTimeMillis: 300000 #空闲连接的最小空闲时间pompokm,
mybatis:
  type-aliases-package: com.zhihu.demo.model #给包中的类注册别名，注册后可以直接使用类名，而不用使用全限定的类名（就是不用包含包名）。
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    jdbc-type-for-null: NULL
  mapper-locations: mapper/projectMapper.xml #mapper文件